### ISSUE TITLE
Use of unstable Rust feature `is_multiple_of` breaks builds on Rust < 1.87

### ISSUE THREAD

**Issue by sipemu** [sipemu/anofox-statistics-rs#4]
## Problem

The crate uses `is_multiple_of()` method on unsigned integers, which is an unstable Rust library feature (`unsigned_is_multiple_of`) that was only stabilized in Rust 1.87.0.

This causes compilation failures when building with Rust versions prior to 1.87.0:

```
error[E0658]: use of unstable library feature `unsigned_is_multiple_of`
   --> src/nonparametric/wilcoxon.rs:491:31
    |
491 |     let estimate = if n_pairs.is_multiple_of(2) {
    |                               ^^^^^^^^^^^^^^
    |
    = note: see issue #128101 <https://github.com/rust-lang/rust/issues/128101> for more information
```

## Affected Files

There are 4 occurrences of `is_multiple_of()`:

1. **src/nonparametric/wilcoxon.rs:491** - `n_pairs.is_multiple_of(2)`
2. **src/nonparametric/wilcoxon.rs:595** - `n_walsh.is_multiple_of(2)`
3. **src/modern/mmd.rs** - `distances.len().is_multiple_of(2)`
4. **src/equivalence/wilcoxon_tost.rs** - `n.is_multiple_of(2)`

## Suggested Fix

Replace all occurrences of `.is_multiple_of(2)` with the equivalent stable expression `% 2 == 0`:

```rust
// Before (requires Rust 1.87+)
if n_pairs.is_multiple_of(2) {

// After (works on all Rust versions)
if n_pairs % 2 == 0 {
```

## Impact

This affects any downstream crates or applications that:
- Use Rust < 1.87.0
- Build for targets where the latest stable Rust isn't available (e.g., some CI environments, WASM builds via emscripten)

## References

- Rust tracking issue: https://github.com/rust-lang/rust/issues/128101
- Stabilization PR: https://github.com/rust-lang/rust/pull/131168 (merged for Rust 1.87.0)
